fs = require 'fs'
path = require 'path'
meta = module.parent.require '../src/meta'
nconf = module.parent.require 'nconf'
SocketModules = module.parent.require './socket.io/modules'
SocketAdmin = module.parent.require './socket.io/admin'
emoji = require 'emoji-images'
Settings = module.parent.require '../src/settings'
